using UnityEngine;

public class Cherry : MonoBehaviour
{
    // tá»‘c Ä‘á»™ rÆ¡i cá»§a quáº£ cherry
    [SerializeField] public float fallSpeed;
    [SerializeField] float killY = -6f;
    [SerializeField] float speedMultiplier = 6.0f;
    // !! UPDATE() CHERRY FUNCTION
    void Update()
    {
        // cho váº­t thá»ƒ rÆ¡i xuá»‘ng
        transform.Translate
        (
            Vector2.down * fallSpeed * Time.deltaTime * speedMultiplier, 
            Space.World
        );
        // Ä‘oáº¡n if nÃ y cÃ³ thá»ƒ k cáº§n cÅ©ng Ä‘c, vÃ¬ Ä‘Ã£ cÃ³ OnTriggerEnter2D vá»›i KillZone rá»“i
        if (transform.position.y < killY)
            CherryPool
                .Instance
                    .ReturnCherry(gameObject);
    }
    // !! ONTRIGGERENTER2D() CHERRY FUNCTION
    void OnTriggerEnter2D(Collider2D other)
    {
        if (other.CompareTag("Player"))
        {
            ScoreManager.Instance.AddScore(5);          // +5

            // ** 19. SEGMENT HIá»‚N THá»Š POPUP ÄIá»‚M KHI NHáº¶T CHERRY
            // ðŸ”¹ Hiá»‡n popup "+5" trÃªn Ä‘áº§u ngÆ°á»i chÆ¡i
            // if (ScorePopupManager.Instance != null)
            // {
            //     ScorePopupManager.Instance.Show(
            //         "+5",
            //         other.transform.position,     // vá»‹ trÃ­ player
            //         Color.green                   // mÃ u text
            //     );
            // }
            // ** END SEGMENT

            // ** 17. PHÃT TIáº¾NG TING TING KHI NHáº¶T CHERRY SEGMENT
            // phÃ¡t Ã¢m thanh nháº·t cherry
            // if (PlayerControllerScript.instance != null)
            // {
            //     PlayerControllerScript.instance.PlayCherryPickupSfx();
            // }
            // ** END SEGMENT

            CherryPool.Instance.ReturnCherry(gameObject);
        }
        else if (other.CompareTag("KillZone"))
        {
            CherryPool.Instance.ReturnCherry(gameObject);
        }
    }
}
